### ISSUE TITLE
Feature request: UniTask support

### ISSUE THREAD

**Issue by JesseTG** [dre0dru/LocalStorage#1]
Have you considered adding support for [UniTask](https://github.com/Cysharp/UniTask) in this library? The API is pretty much the same as that of standard `Task`s, but optimized for Unity. If you wanted to keep `Task` support, you could probably even do it with conditional compilation and `using` aliases.

**Comment by dre0dru** [comment]
@JesseTG Recently discovered Version Defines in Unity assembly definitions and it was my first thought to do it! Also idea with `using` aliases looks nice, will definitely try it out, thanks!
So yes, I will add support for UniTask in next minor update :star_struck:
