### ISSUE TITLE
Proposal: Split async methods into separate interfaces?

### ISSUE THREAD

**Issue by JesseTG** [dre0dru/LocalStorage#2]
Some storage backends only support synchronous APIs. Some only support *asynchronous* APIs. Would it be possible to divide interfaces that have methods for both into synchronous and asynchronous versions?

**Comment by dre0dru** [comment]
@JesseTG Hello! Can you please provide more info on how you view this? As I understand you are talking about `IFileStorage` and `IPlayerPrefsStorage` and they support async and sync API which is defined mostly by underlying `ISerializationProvider`. Default package implementation (`UnityJsonSerializationProvider`) indeed provides only sync API for serialization, but some serialization libraries like [UT8Json](https://github.com/neuecc/Utf8Json) provide async API, too. Also `IDataTransofrm` implementations that can be used with `ISerializationProvider` also have async API.

Right now my only thoughs are something like this:
```c#
interface IFileStorage {
//sync API
}

interface IAsyncFileStorage : IFileStorage {
//addintional async API
}

class FileStorage : IAsyncFileStorage {
// both async and sync implementation
}
```
This way, e.g., you can bind instance to sync or async interface.
Maybe you can provide use case where you need that kind of separation if I misunderstood you?

**Comment by JesseTG** [comment]
No, you understand me correctly.

I don't have a _specific_ use case right now, since I happen to use async APIs in my project, but I'm trying to think a step ahead.
